version: '3.3'

services:
  newbies-web:
    image: ghcr.io/newbies-workplace/newbies-web:latest
    restart: unless-stopped
    container_name: newbies-web
    ports:
      - "3000:3000"
  newbies-db:
    image: postgis/postgis:13-master
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "newbies-web-db"
  newbies-cms:
    image: directus/directus
    ports:
      - "8055:8055"
    volumes:
      - upload-data:/directus/uploads
    depends_on:
      - newbies-db
    environment:
      KEY:
      SECRET:

      DB_CLIENT: "pg"
      DB_HOST: "newbies-db"
      DB_PORT: "5432"
      DB_DATABASE: "newbies-web-db"
      DB_USER:
      DB_PASSWORD:

      ADMIN_EMAIL:
      ADMIN_PASSWORD:

volumes:
  db-data:
  upload-data:
